# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
 name: Default
 vmImage: 'LAPTOP-VQ16APIQ'

variables:
  buildConfiguration: 'Release'
  testDllPath: '$(System.DefaultWorkingDirectory)\bin\Any CPU\Release\net6.0\DemoTestAutomationAPI.dll'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.11.0'
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(System.DefaultWorkingDirectory)/DemoTestAutomationAPI.csproj'
  displayName: 'Restore NuGet packages'
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: 'xml'
    targetFiles: '$(System.DefaultWorkingDirectory)/App.config'
    xmlTransformationRules: |
      <?xml version="1.0" encoding="utf-8"?>
      <configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
        <appSettings>
          <add key="Browser" value="$(Browser)" xdt:Transform="Replace" xdt:Locator="Match(key)"/>
          <add key="baseUrl" value="$(BaseUrl)" xdt:Transform="Replace" xdt:Locator="Match(key)"/>
        </appSettings>
      </configuration>

- task: VSBuild@1
  inputs:
    solution: '$(System.DefaultWorkingDirectory)/DemoTestAutomationAPI.csproj'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'
  displayName: 'Build project'

- task: VSTest@2
  inputs:
    testAssemblyVer2: |
      $(testDllPath)
    searchFolder: '$(System.DefaultWorkingDirectory)'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'
  displayName: 'Run tests'
